# Generated by Django 6.0.6 on 2026-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='emoji',
            field=models.CharField(default='', max_length=255),
        ),
    ]
