# Generated by Django 6.0.6 on 2026-07-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_emoji'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='doctors',
        ),
    ]
